[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
#noipv6#Address = ${CLIENT_IP}/24
#ipv6#Address = ${CLIENT_IP}/24, ${CLIENT_IP6}/64

[Peer]
PublicKey = ${PUBLIC_KEY}
PresharedKey = ${CLIENT_PRESHARED_KEY}
Endpoint = ${SERVER_HOST}:51443
#noipv6#AllowedIPs = 10.29.8.0/24, 8.8.8.8/32, 8.8.4.4/32${IPS}
#ipv6#AllowedIPs = 10.29.8.0/24, 8.8.8.8/32, 8.8.4.4/32${IPS}, fd29:0:0:8::/64${IPS6}
PersistentKeepalive = 15
